---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: my-ingress-nginx
  namespace: task
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: my-app.com
    http:
      paths:
      - path: /web1/index.html
        backend:
          serviceName: web1
          servicePort: 80
      - path: /web2/index.html
        backend:
          serviceName: web2
          servicePort: 80
