---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web1
  namespace: task
  labels:
    app: web1
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: web1
  template:
    metadata:
      labels:
        app: web1
    spec:
      containers:
      - name: web1
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 80
