---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web2
  namespace: task
  labels:
    app: web2
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: web2
  template:
    metadata:
      labels:
        app: web2
    spec:
      containers:
      - name: web2
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 80
